# Generated by Django 4.2.3 on 2023-08-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='unknown@example.com', max_length=40),
        ),
        migrations.AddField(
            model_name='person',
            name='roll_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
